CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
password_hash VARCHAR(100) NOT NULL,
avatar VARCHAR(255),
created_at TIMESTAMP NOT NUll DEFAULT NOW()
);
